package com.example.dhapp.service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

/**
 * {@code /api/config/date-config}、{@code /api/secure-api}、{@code /api/tls} の呼び出し時に、
 * 実際の PDF ファイル（{@code dummy.pdf}）を生成するサービス。
 *
 * <p>従来は Logback のアペンダで処理内容ログを {@code dummy.pdf} という名前のテキストファイルとして
 * 出力していたが、本サービスでは Apache PDFBox を使って「DUMMY」という文字列を書き込んだ
 * 本物の PDF を生成する。</p>
 *
 * <p>出力先は環境変数 {@code DATA_OUTPUT_DIR}（未設定時はカレント配下 {@code ./data}）配下の
 * {@code dummy.pdf} で、テキストファイル版（logback-spring.xml の DUMMY_PDF_FILE）と同一。
 * ディレクトリが存在しない場合は自動作成する。</p>
 */
@Service
public class DummyPdfService {

    private static final Logger log = LoggerFactory.getLogger(DummyPdfService.class);

    /** 生成する PDF のファイル名。テキストファイル版と同じ dummy.pdf。 */
    private static final String PDF_FILE_NAME = "dummy.pdf";

    /** PDF に書き込む文字列。 */
    private static final String PDF_CONTENT = "DUMMY";

    /** データ出力ディレクトリ（DATA_OUTPUT_DIR、未設定時は ./data）。テキストファイル版と同一。 */
    private final String dataOutputDir;

    public DummyPdfService(@Value("${DATA_OUTPUT_DIR:data}") String dataOutputDir) {
        this.dataOutputDir = dataOutputDir;
    }

    /**
     * DATA_OUTPUT_DIR 配下に「DUMMY」と記載した PDF ({@code dummy.pdf}) を生成（上書き）する。
     *
     * <p>PDF 生成に失敗しても REST API 本体の処理は継続させるため、例外は送出せず
     * エラーログの記録のみを行う。</p>
     *
     * @param apiLabel 呼び出し元 API を識別するラベル（ログ用）
     */
    public void createDummyPdf(String apiLabel) {
        Path dir = Paths.get(dataOutputDir);
        Path pdfPath = dir.resolve(PDF_FILE_NAME);
        try {
            Files.createDirectories(dir);
            try (PDDocument document = new PDDocument()) {
                PDPage page = new PDPage();
                document.addPage(page);
                try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                    contentStream.beginText();
                    contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 24);
                    contentStream.newLineAtOffset(100, 700);
                    contentStream.showText(PDF_CONTENT);
                    contentStream.endText();
                }
                document.save(pdfPath.toFile());
            }
            log.debug("dummy.pdf generated by PDFBox. apiLabel={}, path={}", apiLabel, pdfPath.toAbsolutePath());
        } catch (IOException e) {
            // PDF 生成失敗は API 本体を止めない（ログのみ）。
            log.error("Failed to generate dummy.pdf. apiLabel={}, path={}", apiLabel, pdfPath, e);
        }
    }
}
